#!/bin/bash
set -e

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/github
git remote set-url origin git@github.com:mametoff/sfdisk-sys.git
git add -A

git commit -m "Auto update: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

git push origin main
